# Generated by Django 4.2.2 on 2023-10-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produkty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Składnik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("INCI", models.CharField(max_length=300)),
                ("PL", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Skład",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skład_INCI", models.CharField(max_length=300)),
                (
                    "Kosmetyk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Skład",
                        to="produkty.kosmetyk",
                    ),
                ),
            ],
        ),
    ]
