# Generated by Django 4.2.2 on 2024-02-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produkty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skladnik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inci", models.CharField(max_length=100)),
                ("pl", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sklad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sklad_inci", models.CharField(max_length=100)),
                ("sklad_pl", models.CharField(max_length=100)),
                (
                    "kosmetyk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Sklad",
                        to="produkty.kosmetyk",
                    ),
                ),
            ],
        ),
    ]
