# Generated by Django 4.2.2 on 2024-02-25 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kosmetyk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka", models.CharField(max_length=100)),
                ("nazwa", models.CharField(max_length=100)),
                (
                    "owner",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wKosmetyczce",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kosmetyki",
            },
        ),
        migrations.CreateModel(
            name="Rdz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodzaj", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stylizator",
            fields=[
                (
                    "kosmetyk_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produkty.kosmetyk",
                    ),
                ),
                (
                    "hold",
                    models.CharField(
                        choices=[
                            ("Lekki", "Lekki"),
                            ("Średni", "Średni"),
                            ("Mocny", "Mocny"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stylizatory",
            },
            bases=("produkty.kosmetyk",),
        ),
        migrations.CreateModel(
            name="WorkingsKosmetyk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                (
                    "kolejnosc",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produkty.kosmetyk",
                    ),
                ),
            ],
            options={
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Wcierka",
            fields=[
                (
                    "kosmetyk_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produkty.kosmetyk",
                    ),
                ),
                (
                    "Rodzaj",
                    models.ForeignKey(
                        default="Wcierka",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Wcierki",
                        to="produkty.rdz",
                        to_field="rodzaj",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wcierki",
            },
            bases=("produkty.kosmetyk",),
        ),
        migrations.CreateModel(
            name="Szampon",
            fields=[
                (
                    "kosmetyk_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produkty.kosmetyk",
                    ),
                ),
                (
                    "moc",
                    models.CharField(
                        choices=[
                            ("Łagodny", "Łagodny"),
                            ("Średni", "Średni"),
                            ("Rypacz (mocny)", "Rypacz (mocny)"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "rodzaj",
                    models.ForeignKey(
                        default="Szampon",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="szampony",
                        to="produkty.rdz",
                        to_field="rodzaj",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Szampony",
            },
            bases=("produkty.kosmetyk",),
        ),
        migrations.CreateModel(
            name="Peeling",
            fields=[
                (
                    "kosmetyk_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produkty.kosmetyk",
                    ),
                ),
                (
                    "Rodzaj",
                    models.ForeignKey(
                        default="Peeling",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Peelingi",
                        to="produkty.rdz",
                        to_field="rodzaj",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Peelingi",
            },
            bases=("produkty.kosmetyk",),
        ),
        migrations.CreateModel(
            name="Olejek",
            fields=[
                (
                    "kosmetyk_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produkty.kosmetyk",
                    ),
                ),
                (
                    "Rodzaj",
                    models.ForeignKey(
                        default="Olejek",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Olejki",
                        to="produkty.rdz",
                        to_field="rodzaj",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Olejki",
            },
            bases=("produkty.kosmetyk",),
        ),
        migrations.CreateModel(
            name="Olej",
            fields=[
                (
                    "kosmetyk_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produkty.kosmetyk",
                    ),
                ),
                (
                    "Rodzaj",
                    models.ForeignKey(
                        default="Olej",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Oleje",
                        to="produkty.rdz",
                        to_field="rodzaj",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Oleje",
            },
            bases=("produkty.kosmetyk",),
        ),
        migrations.CreateModel(
            name="Odzywka",
            fields=[
                (
                    "kosmetyk_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produkty.kosmetyk",
                    ),
                ),
                (
                    "PEH",
                    models.CharField(
                        choices=[
                            ("Humektantowa", "Humektantowa"),
                            ("Proteinowa", "Proteinowa"),
                            ("Emolientowa", "Emolientowa"),
                            ("Emolientowo - humektantowa", "EH"),
                            ("PEH'owa", "PEH"),
                            ("Humektantowo - emolientowa", "HE"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "Rodzaj",
                    models.ForeignKey(
                        default="Odzywka",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Odzywki",
                        to="produkty.rdz",
                        to_field="rodzaj",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Odzywki",
            },
            bases=("produkty.kosmetyk",),
        ),
        migrations.CreateModel(
            name="Maska",
            fields=[
                (
                    "kosmetyk_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produkty.kosmetyk",
                    ),
                ),
                (
                    "PEH",
                    models.CharField(
                        choices=[
                            ("Humektantowa", "Humektantowa"),
                            ("Proteinowa", "Proteinowa"),
                            ("Emolientowa", "Emolientowa"),
                            ("Emolientowo - humektantowa", "EH"),
                            ("PEH'owa", "PEH"),
                            ("Humektantowo - emolientowa", "HE"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "Rodzaj",
                    models.ForeignKey(
                        default="Maska",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Maski",
                        to="produkty.rdz",
                        to_field="rodzaj",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Maski",
            },
            bases=("produkty.kosmetyk",),
        ),
        migrations.CreateModel(
            name="Zel",
            fields=[
                (
                    "stylizator_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produkty.stylizator",
                    ),
                ),
                (
                    "Rodzaj",
                    models.ForeignKey(
                        default="Zel",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Zele",
                        to="produkty.rdz",
                        to_field="rodzaj",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Zele",
            },
            bases=("produkty.stylizator",),
        ),
        migrations.CreateModel(
            name="Pianka",
            fields=[
                (
                    "stylizator_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produkty.stylizator",
                    ),
                ),
                (
                    "Rodzaj",
                    models.ForeignKey(
                        default="Pianka",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pianki",
                        to="produkty.rdz",
                        to_field="rodzaj",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pianki",
            },
            bases=("produkty.stylizator",),
        ),
        migrations.CreateModel(
            name="Krem",
            fields=[
                (
                    "stylizator_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produkty.stylizator",
                    ),
                ),
                (
                    "Rodzaj",
                    models.ForeignKey(
                        default="Krem",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Kremy",
                        to="produkty.rdz",
                        to_field="rodzaj",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kremy",
            },
            bases=("produkty.stylizator",),
        ),
    ]
