# Generated by Django 4.2.2 on 2024-01-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produkty", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maska",
            name="PEH",
            field=models.CharField(
                choices=[
                    ("Proteinowa", "Proteinowa"),
                    ("PEH'owa", "PEH"),
                    ("Humektantowa", "Humektantowa"),
                    ("Humektantowo - emolientowa", "HE"),
                    ("Emolientowo - humektantowa", "EH"),
                    ("Emolientowa", "Emolientowa"),
                ],
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="odżywka",
            name="PEH",
            field=models.CharField(
                choices=[
                    ("Proteinowa", "Proteinowa"),
                    ("PEH'owa", "PEH"),
                    ("Humektantowa", "Humektantowa"),
                    ("Humektantowo - emolientowa", "HE"),
                    ("Emolientowo - humektantowa", "EH"),
                    ("Emolientowa", "Emolientowa"),
                ],
                max_length=300,
            ),
        ),
    ]
