# Generated by Django 4.2.2 on 2024-02-25 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wlosy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dlugosc",
                    models.CharField(
                        choices=[
                            ("Krótkie", "Krótkie - do ramion"),
                            ("Średnie", "Średnie - za ramiona"),
                            ("Długie", "Długie - za łopatki"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "kolor",
                    models.CharField(
                        choices=[
                            ("Blond", "Blond"),
                            ("Szatynka", "Szatynka"),
                            ("Brunetka", "Brunetka"),
                            ("Rude", "Rude"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "porowatosc",
                    models.CharField(
                        choices=[
                            ("Wysokoporowate", "Wysokoporowate"),
                            ("Średnioporowate", "Średnioporowate"),
                            ("Niskoporowate", "Niskoporowate"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("Proste", "Proste - brak skrętu"),
                            ("Falowane", "Falowane - typ 2a, 2b lub 2c"),
                            ("Wurly", "Wurly - uzupełnij"),
                            ("Kręcone", "Kręcone - typ 3a, 3b lub 3c"),
                            ("Afro", "Afro - typ 4"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "owner",
                    models.ManyToManyField(
                        blank=True,
                        related_name="typ_wlosow",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
