# Generated by Django 4.2.2 on 2023-10-12 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Włosy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Długość",
                    models.CharField(
                        choices=[
                            ("Krótkie - do ramion", "Krótkie - do ramion"),
                            ("Średnie - za ramiona", "Średnie - za ramiona"),
                            ("Długie - za łopatki", "Długie - za łopatki"),
                        ],
                        max_length=300,
                    ),
                ),
                (
                    "Kolor",
                    models.CharField(
                        choices=[
                            ("Blond", "Blond"),
                            ("Szatynka", "Szatynka"),
                            ("Brunetka", "Brunetka"),
                            ("Rude", "Rude"),
                        ],
                        max_length=300,
                    ),
                ),
                (
                    "Porowatość",
                    models.CharField(
                        choices=[
                            ("Wysokoporowate", "Wysokoporowate"),
                            ("Średnioporowate", "Średnioporowate"),
                            ("Niskoporowate", "Niskoporowate"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "Typ",
                    models.CharField(
                        choices=[
                            ("Proste", "Proste - brak skrętu"),
                            ("Falowane", "Falowane - typ 2a, 2b lub 2c"),
                            ("Wurly", "Wurly - uzupełnij"),
                            ("Kręcone", "Kręcone - typ 3a, 3b lub 3c"),
                            ("Afro", "Afro - typ 4"),
                        ],
                        max_length=300,
                    ),
                ),
                (
                    "Owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Użytkownik",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
